### ISSUE TITLE
Self-Bots arent allowed.

### ISSUE THREAD

**Issue by retrievaaaa** [Awire9966/DiscordScamStopper#1]
Discord ToS does prohibit the use of self bots. DO NOT USE THIS PROGRAM - discord can and will ban you if they notice that you are using a self bot.

See https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-

**Comment by Awire9966** [comment]
Yes but discord also prohibits scams. And IF you want, i could give you an array of sites that are somehow NOT filtered by discord.
And if your wondering, yes they are scamming sites

**Comment by retrievaaaa** [comment]
That doesn't change the fact that they ban you for self botting. Discord doesnt give a fuck about what the reason to self botting is.

**Comment by retrievaaaa** [comment]
Its discord god damn, ever talked to their support? lmfao

**Comment by retrievaaaa** [comment]
@Awire9966 I recommend you to take this project down as Discord does not care for what reason you are self botting. By not even adding a warning, you are indirectly causing people to get banned. And those people that get banned are NOT the scammers.

I understand that this is supposed to be something nice and wants to protect people, but self-bots are simply not allowed. Discord is very strict about this. One of my alts got banned for using a self-bot. They will notice it at some point and ban you. Good luck trying to talk to anyone from the support then, they will simply ignore you :D

**Comment by Awire9966** [comment]
First off i would like to mention to you that my friend reported someone on discord (it was a legit report) and he got banned. Second, I will take this down when discord implements this feature. Third off if you havent been hit by scams your lucky.

**Comment by retrievaaaa** [comment]
> I will take this down when discord implements this feature
# Discord already has. It has been a feature for multiple weeks now.
![image](https://user-images.githubusercontent.com/49924528/160286600-caed269c-178c-40f5-b09a-9e3c5f79bdff.png)


Also, it doesn't matter if scamming is against the, rules, self bots are also against the rules. Its like killing someone because he killed your mother. Not allowed.

> Automating normal user accounts (generally called "self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found. (https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-)

Its discord. Good luck getting your account unbanned if they ban you for using a self-bot! (hint: its not possible!)

@Awire9966

**Comment by Awire9966** [comment]
yea but thats one of the obvious websites.

**Comment by retrievaaaa** [comment]
@Awire9966 every real scam site in your list you probably stole from the internet is also blocked by discord. What the fuck do you not understand about "IT IS NOT ALLOWED"?

And why the fuck are sites like telegra.ph in that list? its a legit website unrelated to discord? That just shows that this list is stolen, because maybe it used to be scam but that was quite a while ago, since domains cant be used for i think it was 30 days after expiration

**Comment by retrievaaaa** [comment]
I just checked and telegra.ph was always a legit website (archive.org) so idk what the fuck you have been smoking when "making" that list
